# Generated by Django 5.0.4 on 2024-05-08 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labpro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="labs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="labpro.labs",
            ),
        ),
    ]
