# Generated by Django 5.0.4 on 2024-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labpro", "0003_remove_timetable_labs"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="capacity_lab1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="capacity_lab2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="capacity_lab3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="capacity_lab4",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="capacity_lab5",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="items_1",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name="timetable",
            name="items_2",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name="timetable",
            name="items_3",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name="timetable",
            name="items_4",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name="timetable",
            name="items_5",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name="timetable",
            name="lab_1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="lab_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="lab_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="lab_4",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="lab_5",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="time_10_11",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="time_11_12",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="time_12_13",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="time_13_14",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="time_9_10",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
