# Generated by Django 5.0.4 on 2024-05-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labpro", "0004_timetable_capacity_lab1_timetable_capacity_lab2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timetable",
            old_name="time_10_11",
            new_name="time_1",
        ),
        migrations.RenameField(
            model_name="timetable",
            old_name="time_11_12",
            new_name="time_2",
        ),
        migrations.RenameField(
            model_name="timetable",
            old_name="time_12_13",
            new_name="time_3",
        ),
        migrations.RenameField(
            model_name="timetable",
            old_name="time_13_14",
            new_name="time_4",
        ),
        migrations.RenameField(
            model_name="timetable",
            old_name="time_9_10",
            new_name="time_5",
        ),
    ]
