# Generated by Django 5.0.4 on 2024-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labpro", "0005_rename_time_10_11_timetable_time_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timetable",
            old_name="time_1",
            new_name="end_time_1",
        ),
        migrations.RenameField(
            model_name="timetable",
            old_name="time_2",
            new_name="end_time_2",
        ),
        migrations.RenameField(
            model_name="timetable",
            old_name="time_3",
            new_name="end_time_3",
        ),
        migrations.RenameField(
            model_name="timetable",
            old_name="time_4",
            new_name="end_time_4",
        ),
        migrations.RenameField(
            model_name="timetable",
            old_name="time_5",
            new_name="end_time_5",
        ),
        migrations.AddField(
            model_name="timetable",
            name="start_time_1",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="start_time_2",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="start_time_3",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="start_time_4",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="start_time_5",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
