# Generated by Django 5.0.4 on 2024-05-08 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labpro", "0007_feedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Feedback",
            new_name="Feedback1",
        ),
    ]
