# Generated by Django 5.0.4 on 2024-05-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labpro", "0009_timetableentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimetableEntry",
        ),
    ]
