# Generated by Django 5.0.4 on 2024-05-19 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labpro", "0010_delete_timetableentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Feedback1",
            new_name="Feedback",
        ),
    ]
