# Generated by Django 5.0.4 on 2024-05-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_remove_department_institution"),
        ("labpro", "0011_rename_feedback1_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labs",
            old_name="capacity_lab1",
            new_name="capacity",
        ),
        migrations.RenameField(
            model_name="labs",
            old_name="items_1",
            new_name="items",
        ),
        migrations.RenameField(
            model_name="labs",
            old_name="lab_1",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="labs",
            name="capacity_lab2",
        ),
        migrations.RemoveField(
            model_name="labs",
            name="capacity_lab3",
        ),
        migrations.RemoveField(
            model_name="labs",
            name="capacity_lab4",
        ),
        migrations.RemoveField(
            model_name="labs",
            name="items_2",
        ),
        migrations.RemoveField(
            model_name="labs",
            name="items_3",
        ),
        migrations.RemoveField(
            model_name="labs",
            name="items_4",
        ),
        migrations.RemoveField(
            model_name="labs",
            name="lab_2",
        ),
        migrations.RemoveField(
            model_name="labs",
            name="lab_3",
        ),
        migrations.RemoveField(
            model_name="labs",
            name="lab_4",
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.department",
                    ),
                ),
                (
                    "labs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="labpro.labs"
                    ),
                ),
            ],
        ),
    ]
