# Generated by Django 5.0.4 on 2024-05-20 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_remove_department_institution"),
        ("labpro", "0013_remove_timetable_capacity_lab1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="day_of_week",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Authentication.department",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Authentication.institution",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="lab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="labpro.labs"
            ),
        ),
    ]
