# Generated by Django 5.0.4 on 2024-05-20 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_remove_department_institution"),
        ("labpro", "0014_alter_timetable_day_of_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labs",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Authentication.department",
            ),
        ),
    ]
