# Generated by Django 5.0.4 on 2024-05-20 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_remove_department_institution"),
        ("labpro", "0015_labs_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labs",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="labs",
            name="department",
        ),
        migrations.RemoveField(
            model_name="labs",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="labs",
            name="items",
        ),
        migrations.CreateModel(
            name="Labs_show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.IntegerField(blank=True, null=True)),
                ("items", models.TextField(blank=True, max_length=1500)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.department",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.institution",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        blank=True,
                        max_length=100,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labpro.labs",
                    ),
                ),
            ],
        ),
    ]
