# Generated by Django 5.0.6 on 2024-05-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labpro", "0020_labs_show_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="labs_show",
            name="day",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
