# Generated by Django 5.0.6 on 2024-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labpro", "0023_practicaltimetable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practicaltimetable",
            name="day",
        ),
        migrations.AddField(
            model_name="practicaltimetable",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
