# Generated by Django 5.0.4 on 2024-05-06 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0002_department_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Authentication.institution",
            ),
        ),
    ]
