# Generated by Django 5.0.4 on 2024-05-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0003_department_institution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="institution",
        ),
    ]
