# Generated by Django 5.0.4 on 2024-05-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0002_equipments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labs', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
