# Generated by Django 5.0.4 on 2024-05-01 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0003_labs'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laballocation.labs'),
        ),
    ]
