# Generated by Django 5.0.4 on 2024-05-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0004_equipments_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='Items',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='lab',
        ),
    ]
