# Generated by Django 5.0.4 on 2024-05-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0006_equipments_items_1_equipments_items_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='department',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='location',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
    ]
