# Generated by Django 5.0.4 on 2024-05-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0007_remove_timetable_day_remove_timetable_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='institution',
        ),
        migrations.AddField(
            model_name='timetable',
            name='clas',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
