# Generated by Django 5.0.4 on 2024-05-01 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_department_profile'),
        ('Laballocation', '0008_remove_timetable_institution_timetable_clas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='clas',
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timetable',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.department'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time_1',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time_2',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time_3',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time_4',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time_5',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.institution'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='location_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_location_1', to='Laballocation.labs'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='location_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_location_2', to='Laballocation.labs'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='location_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_location_3', to='Laballocation.labs'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='location_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_location_4', to='Laballocation.labs'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='location_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_location_5', to='Laballocation.labs'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time_1',
            field=models.TimeField(default='11:00'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time_2',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time_3',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time_4',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time_5',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
