# Generated by Django 5.0.4 on 2024-05-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0009_remove_timetable_clas_timetable_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='subject_1',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_2',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_3',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_4',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_5',
        ),
    ]
