# Generated by Django 5.0.4 on 2024-05-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0011_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
