# Generated by Django 5.0.4 on 2024-05-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0013_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
    ]
