# Generated by Django 5.0.4 on 2024-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0014_remove_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
