# Generated by Django 5.0.4 on 2024-05-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_department_profile'),
        ('Laballocation', '0015_labs_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.institution'),
        ),
    ]
