# Generated by Django 5.0.4 on 2024-05-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0016_labs_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labs',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='location_5',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='location_4',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='location_1',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='location_3',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='location_2',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='department',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Equipments',
        ),
        migrations.DeleteModel(
            name='Labs',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
