# Generated by Django 5.0.4 on 2024-05-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_department_profile'),
        ('Laballocation', '0017_remove_labs_institution_remove_timetable_location_5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labs', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField()),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.institution')),
            ],
        ),
    ]
