# Generated by Django 5.0.4 on 2024-05-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0018_labs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labs',
        ),
    ]
