# Generated by Django 5.0.4 on 2024-05-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_department_profile'),
        ('Laballocation', '0019_delete_labs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labs', models.IntegerField(unique=True)),
                ('capacity_lab1', models.IntegerField(blank=True, null=True)),
                ('items_1', models.TextField(blank=True, max_length=1500)),
                ('capacity_lab2', models.IntegerField(blank=True, null=True)),
                ('items_2', models.TextField(blank=True, max_length=1500)),
                ('capacity_lab3', models.IntegerField(blank=True, null=True)),
                ('items_3', models.TextField(blank=True, max_length=1500)),
                ('capacity_lab4', models.IntegerField(blank=True, null=True)),
                ('items_4', models.TextField(blank=True, max_length=1500)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.institution')),
                ('lab_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_1_set', to='Laballocation.labs')),
                ('lab_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_2_set', to='Laballocation.labs')),
                ('lab_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_3_set', to='Laballocation.labs')),
                ('lab_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_4_set', to='Laballocation.labs')),
            ],
        ),
    ]
