# Generated by Django 5.0.4 on 2024-05-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0021_timetable_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='period_number',
        ),
    ]
