# Generated by Django 5.0.4 on 2024-05-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0022_remove_period_period_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labs',
            name='capacity_lab1',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='capacity_lab2',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='capacity_lab3',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='capacity_lab4',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='items_1',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='items_2',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='items_3',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='items_4',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='lab_1',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='lab_2',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='lab_3',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='lab_4',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='labs',
        ),
    ]
