# Generated by Django 5.0.4 on 2024-05-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0023_remove_labs_capacity_lab1_remove_labs_capacity_lab2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='capacity_lab1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='capacity_lab2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='capacity_lab3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='capacity_lab4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='items_1',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='labs',
            name='items_2',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='labs',
            name='items_3',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='labs',
            name='items_4',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='labs',
            name='lab_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='lab_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='lab_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='lab_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
