# Generated by Django 5.0.4 on 2024-05-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0024_labs_capacity_lab1_labs_capacity_lab2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
