# Generated by Django 5.0.4 on 2024-05-06 03:38

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0026_alter_period_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='location',
            field=models.ForeignKey(blank=True, limit_choices_to={'institution': django.db.models.expressions.OuterRef('timetable__institution_id')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laballocation.labs'),
        ),
    ]
