# Generated by Django 5.0.4 on 2024-05-06 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laballocation', '0027_alter_period_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laballocation.labs'),
        ),
    ]
