# Generated by Django 5.0.4 on 2024-05-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Laballocation", "0028_alter_period_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetable",
            name="department",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="institution",
        ),
        migrations.DeleteModel(
            name="Period",
        ),
    ]
