# Generated by Django 5.0.4 on 2024-05-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0003_department_institution"),
        ("Laballocation", "0029_remove_timetable_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Authentication.department",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Authentication.institution",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
