# Generated by Django 5.0.4 on 2024-05-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Laballocation",
            "0031_remove_timetable_day_remove_timetable_end_time_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetable",
            name="labs",
        ),
        migrations.AddField(
            model_name="timetable",
            name="capacity_lab1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="capacity_lab2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="capacity_lab3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="capacity_lab4",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="items_1",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name="timetable",
            name="items_2",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name="timetable",
            name="items_3",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name="timetable",
            name="items_4",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name="timetable",
            name="lab_1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="lab_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="lab_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="lab_4",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
