# Generated by Django 5.0.4 on 2024-05-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Laballocation", "0033_remove_timetable_department_labs_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetable",
            name="capacity_lab1",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="capacity_lab2",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="capacity_lab3",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="capacity_lab4",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="items_1",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="items_2",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="items_3",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="items_4",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="lab_1",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="lab_2",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="lab_3",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="lab_4",
        ),
    ]
