# Generated by Django 5.0.4 on 2024-05-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Laballocation", "0034_remove_timetable_capacity_lab1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labs",
            name="department",
        ),
    ]
