# Generated by Django 5.0.4 on 2024-05-08 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Laballocation", "0035_remove_labs_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="labs",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Laballocation.labs",
            ),
        ),
    ]
