# Generated by Django 5.0.4 on 2024-05-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Laballocation", "0036_timetable_labs"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="lab_session_1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="lab_session_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="lab_session_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="lab_session_4",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
