# Generated by Django 5.0.4 on 2024-05-08 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_remove_department_institution"),
        (
            "Laballocation",
            "0037_timetable_lab_session_1_timetable_lab_session_2_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetable",
            name="lab_session_1",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="lab_session_2",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="lab_session_3",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="lab_session_4",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="labs",
        ),
        migrations.AddField(
            model_name="timetable",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Authentication.department",
            ),
        ),
    ]
