# Generated by Django 5.0.4 on 2024-05-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Laballocation", "0038_remove_timetable_lab_session_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetable",
            name="department",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="institution",
        ),
        migrations.DeleteModel(
            name="Labs",
        ),
        migrations.DeleteModel(
            name="Timetable",
        ),
    ]
