# Generated by Django 5.0.4 on 2024-05-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_remove_department_institution"),
        ("Laballocation", "0039_remove_timetable_department_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Messsage",
            new_name="Message",
        ),
    ]
