# Generated by Django 5.0.4 on 2024-05-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Laballocation", "0040_rename_messsage_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="content",
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
